### ISSUE TITLE
Input files for ImRep

### ISSUE THREAD

**Issue by PoslavskySV** [mandricigor/imrep#10]
Hi, 

according to [wiki](https://github.com/mandricigor/imrep/wiki/ImReP-input) I can't just use raw `.fastq` files. Instead, I need to map raw reads with some external aligner and then extract reads somehow  from `.bam` in order to make the data suitable for ImRep. So, could you please help with the following issues:

1.  Which aligner (TopHat, STAR etc.) should I use for aligning the raw `.fastq` data in order to obtain `.bam`?
2. When I have prepared `.bam` (e.g. using STAR aligner and including unmapped reads into the same `.bam` file with `--outSAMunmapped Within` option) what exact bash commands (using `samtools` or either) should I execute in order to produce a valid `.fastq` file that is suitable for ImRep?

Thanks!

**Comment by smangul1** [comment]
Hi, 

We would recommend running ROP pipeline, which includes the latest imrep version and will extract reads mapped to BCR and TCr genes plus unmapped reads from the bam file. We had a good experience with STAR, so i think this is a good option.  Make sure to run with --outSAMunmapped Within option to include unmapped reads in the bam file. 

We are planning to push new release of ROP today. We will let you know once it is available. 

Some information is here:

https://github.com/smangul1/rop/wiki/Immune-profiling-by-ROP-(ImReP)

Thanks, 
Serghei and Igor
