### ISSUE TITLE
TRG

### ISSUE THREAD

**Issue by smangul1** [mandricigor/imrep#14]
please add number of TRG CDR3 reported as well 

Serghei

**Comment by mandricigor** [comment]
Please explain

**Comment by smangul1** [comment]
in this report you don't have TRG chain

843 full CDR3 found:

- 355 of type TRA

- 11 of type TRB

- 2 of type TRD

- 37 of type IGL

- 29 of type IGK

- 409 of type IGH


Only TRA, TRB, TRD

**Comment by mandricigor** [comment]
I show just non zero ones

**Comment by smangul1** [comment]
Please change to add zeros as well

Otherwise it is confusing

**Comment by mandricigor** [comment]
Updated.
