### ISSUE TITLE
Total number of reads mapped to CDR3

### ISSUE THREAD

**Issue by smangul1** [mandricigor/imrep#15]
Can you please report total number of reads mapped to CDR3 per chain besides unique CDR3

Also i still don't see the flag for chain type 

Now it is hard to extract only CDR3 of certain type

Given the flag , we can do this 

awk '{if($5=="IGH") print }'

Does it makes sense?

**Comment by mandricigor** [comment]
Please, explain what kind of flag. For the chain type? We have not discussed this yet, so why "still"....

**Comment by smangul1** [comment]
I though we discussed long time agao
Anyways 
just a flag= IGH,IGK, etc

right now the only way to extract certain chain is by grep which is not the best way 
just make field 2 to be this flag

**Comment by mandricigor** [comment]
Updated
