### ISSUE TITLE
save partialcdr3 at the same dir where full cdr3 are saved

### ISSUE THREAD

**Issue by smangul1** [mandricigor/imrep#16]
for exampel if  run 

python /u/home/b/brigitta/code/imrep/imrep.py --fastq --extendedOutput /u/home/b/brigitta/scratch/dumsterDiving/fastq/A06.fastq /u/home/b/brigitta/scratch/dumsterDiving/rop3/A06/A06.cdr3

i want partial to be in /u/home/b/brigitta/scratch/dumsterDiving/rop3/A06/

**Comment by mandricigor** [comment]
Updated.
