### ISSUE TITLE
incorrect read names in partial_cdr3.txt

### ISSUE THREAD

**Issue by smangul1** [mandricigor/imrep#19]
HW-ST997:187:D1YJGACXX:6:1304:14317:57554/2/1   CSVGSGRGIPGPRASTSAHTQPPAGGFLLLPGQ       TRBV29/OR9,TRBV29       NA      NA      TRBV29/OR9-2*02:4:1,TRBV29-1*02:4:1,TRBV29-1*01:4:1,TRBV29/OR9-2*01:4:1 NA      0       0       0

Correct read names is HW-ST997:187:D1YJGACXX:6:1304:14317:57554/2

**Comment by mandricigor** [comment]
Please attach file and command. Thanks.

**Comment by mandricigor** [comment]
Solved.
