### ISSUE TITLE
additional output

### ISSUE THREAD

**Issue by smangul1** [mandricigor/imrep#3]
Let's make this output per chain

CLLKLSILSNCVLKWYLKQVVLKGLLF 1
CCSAVRVIPFVLHQPLCLPCLKLLQFLLRQLFQCF 2

where CDD3 and number of reads supporting it

How do you think we need to deal wth partial overlapping reads? Count them? In case CDR3 was assembled from 2 partially-mapped reads, should count be 2?

**Comment by mandricigor** [comment]
Could you please explain your comment in more details? I do not understand it.

**Comment by mandricigor** [comment]
Made count be 2 (as sum of counts for partially overlapping reads).
