### ISSUE TITLE
Does imrep work with BAM files from HISAT2 aligner?

### ISSUE THREAD

**Issue by ooondrej** [mandricigor/imrep#33]
Hi, I trying to apply imrep on my bulk paired-end RNA seq data aligned with HISAT2 to hg38 (ucsc). Does the BAM have to come from STAR? I am having this error message ValueError: invalid reference `14`which is most likely caused by alignment to a different reference than imrep is using? What reference is imrep using? 

Many thanks for your help!

**Comment by smangul1** [comment]
Hi,

I expect the build have chromosome names as : chr1, chr2, etc

If this is true you to use this option : --chrFormat2

Alos please make sure to use --hg38 option 

Thanks,
Serghei

**Comment by ooondrej** [comment]
Hi Serghei, many thanks for your advice - it is working brilliantly now!  BW, Ondrej

**Comment by smangul1** [comment]
Great! I am closing the issue then! S
