### ISSUE TITLE
full_cdr3.txt

### ISSUE THREAD

**Issue by smangul1** [mandricigor/imrep#4]
does it contain the CDR3 assembled from 2 reads in by the second step of imrep?
if yes, do we flag for it to distinguish reads overlapping both V and J?

**Comment by mandricigor** [comment]
No, we don't do. Should we have such a flag in full_cdr3.txt?

**Comment by smangul1** [comment]
i think it will be great to have it

**Comment by smangul1** [comment]
Any updates here?

**Comment by mandricigor** [comment]
Do we really need it? Many of the CDR3s that are assembled from one single reads also are assembled overlapping ones. So most of the times we will have both of them to have place.

**Comment by smangul1** [comment]
agree! we don't need it
